trigger:
  batch: true
  branches:
    include:
      - master

variables:
  buildPlatform: 'Any CPU'
  Configuration: 'Release'
  isPullRequest: ${{ and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.PullRequestId'], 'Null')) }}

jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core Sdk 7.0.x'
        inputs:
          version: '7.0.x'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          projects: 'src/**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: build
          projects: 'src/**/Dog.Api.csproj'
          publishWebProjects: false
          zipAfterPublish: ${{ eq(variables.IsPullRequest, 'False') }}
          arguments: '==no-restore --no-build -c $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          ArtifactName: artifacts
  - job: Test
    displayName: 'Test'
    dependsOn: Build
    condition: eq(variables.IsPullRequest, 'True')
    pool:
      name: OCAS Int Pool
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'artifacts'
          path: $(Build.ArtifactStagingDirectory)/artifacts
      - task: UseDotNet@2
        displayName: 'Use DotNet 7.0.x'
        inputs:
          packageType: sdk
          version: '7.0.x'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          feedsToUse: 'config'
          nugetConfigPath: 'src/nuget.config'
          projects: 'src/**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: test
          projects: 'src/Dog.Api.*Tests/*.csproj'
          arguments: '--no-restore -c $(Configuration) --collect "Code coverage""'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        displayName: 'Publish Test Results **\*.trx'
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '**\*.trx'
          mergeTestResults: true
