global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using FluentAssertions;
global using Xunit;
global using Dog.Api.Application;
global using Dog.Api.Core;
global using Dog.Api.Dtos;
global using Dog.Api.IntegrationTests.Fixtures;
global using Dog.Api.TestFramework.Fixtures;