global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using Dog.Api.Core;
global using Dog.Api.Core.Errors;
global using Dog.Api.Core.Models;
global using Dog.Api.Infrastructure.Contexts;
