version: '3.4'

services:
  dog.api:
    image: ${DOCKER_REGISTRY-}dogapi
    container_name: app
    environment:
        ASPNETCORE_ENVIRONMENT: "Docker"
    env_file:
        - variables.env
    ports:
        - 5000:5000
    build:
      context: .
      dockerfile: Dog.Api/Dockerfile
      args:
        USER: DogApi
        GROUP: DogApiGroup
    depends_on:
        - mssql
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
       ACCEPT_EULA: Y
    ports: 
        - 5341:80
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dB
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: Password1!
    ports:
        - 1433:1433


